baseURL = 'https://mikepurdy.dev'
languageCode = 'en-us'
title = 'mikepurdy.dev'
theme = 'slick'
copyright = 'Mike Purdy'
enableEmoji = true

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true               # Allow html (needed for some shortcodes)
    [markup.highlight]
        codeFences = true               # Enable highlighting inside codefences
        guessSyntax = true              # Highlight code without language tag
        noClasses = false               # Use the theme's style sheet

canonifyURLs = true

# Configure pagination
[pagination]
    pagerSize = 99
    path = "page"

[params]
    # Site subtitle (not shown if commented out or set to false)
    #subtitle = "Showcase page"

    # Site description
    description = "My personal site"

    # Favicon file (relative to baseURL - place in assets folder)
    favicon = "favicon.ico"

    # Define formatting of dates
    # (optional, falls back to RFC822 format if not set)
    # For reference to date and time formatting, see:
    # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
    # Make sure to set showMetaDates to true to see any dates
    dateFmt = "20060102"

    # Configure author information
    author.name = "Mike Purdy"
    author.email = "michaeljosephpurdy@gmail.com"
    # It is also possible to use this, but it won't show up in feeds
    # author = "Some Author"

    # Customize the text of the 404 page here
    errorPageText = "This page doesn't exist :/"

    # Define ordering by parameter - anything from the frontmatter is possible
    # Popular options would be "date" (default), "weight", "title", "publishdate"
    #orderPageParam = "d"
    # Reverse the ordering from above
    #orderPageReverse = false

    # Header with title/subtitle can be disabled here.
    # (If you disable this, add some link on the index page inside menu.main,
    #  otherwise your visitors will get confused and lost...)
    showNavHeader = true

    # If false the RSS link in footer is not shown
    showRssLink = true

    # Decide if only summaries are shown on the main page or the full content
    showFullContent = true

    # If false no pagination is shown when there is nothing to paginate
    showEmptyPagination = false

    # If false the title, dates and taxonomy are not shown on single view
    showMeta = true

    # If false the dates for the posts are not shown
    showMetaDates = true

    # If false the taxonomy links for the posts are not shown
    showMetaLinks = true

    # Uses Hugo internal templates if set
    opengraph = false
    schema = false
    twitter_cards = false

    # Example: Store location of assets here.
    # See "head.html" partial on how to include them
    [params.custom]
        #script = "custom.js"
        #style = "custom.css"


# Define all supported taxonomies (add series to the default)
[taxonomies]
    tags = "tags"
    categories = "categories"
    series = "series"

[services.rss]
    # limit the length of the rss feed (default: unlimited)
    #limit = 0

[menu]
    # Configure main menu entries (header)
    # Currently set to list all taxonomies and posts
    [[menu.main]]
        identifier = "game"
        name = "games"
        title = "all games"
        pageref = "/games"
        weight = 1

    [[menu.main]]
        identifier = "post"
        name = "blog"
        title = "Blog"
        pageref = "/posts"
        weight = 2

    [[menu.main]]
        identifier = "tags"
        name = "tags"
        title = "All tags"
        pageref = "/tags"
        weight = 3

    [[menu.main]]
        identifier = "resume"
        name = "resume"
        title = "Resume"
        url = "https://mikepurdy.dev/resume.pdf"
        weight = 4

    #[[menu.main]]
        #identifier = "series"
        #name = "Series"
        #title = "All series"
        #pageref = "/series"
        #weight = 2


    # Define the entries for post metadata
    # Identifiers should match with the taxonomy entries
    [[menu.meta]]
        identifier = "categories"
        name = "Categories"
        weight = 1
    #[[menu.meta]]
        #identifier = "series"
        #name = "Series"
        #weight = 2
    [[menu.meta]]
        identifier = "tags"
        name = "Tags"
        weight = 3


    # Add some footer links to your likings
    [[menu.footer]]
        name = "github"
        title = "repo"
        url = "https://github.com/michaeljosephpurdy"
        weight = 1

    [[menu.footer]]
        name = "itch.io"
        title = "itch.io"
        url = "https://purdy.itch.io"
        weight = 3


# Enable generation of robots.txt
enableRobotsTXT = true

# Configure sitemap
[sitemap]
  # Values are 'always', 'hourly', 'daily',' weekly', 'monthly', 'yearly',
  # and 'never'. Set to empty string to omit inclusion
  changefreq = "monthly"
  # Adjust filename of sitemap. (default: sitemap.xml)
  filename = "sitemap.xml"
  # Values range from 0.0 to 1.0. Set to -1 to omit inclusion
  priority =  -1
